### PR TITLE
updated the file from index.md to readme.md

### PR DESCRIPTION
**Pull request by theabhayprajapati**

### CODE REVIEW

**Review by theabhayprajapati — COMMENTED** [review]
Now one see the contents directly, with the help of readme.md file name

**Review by KendallDoesCoding — COMMENTED** [review]
I didn't do this because I thought then the user will have to add extra to the url, please confirm if the url https://kendalldoescoding.github.io/Best-Hosting-Service/ will work if I mere this PR or if it will have to be https://kendalldoescoding.github.io/Best-Hosting-Service/README.md/

**Comment by theabhayprajapati** [comment]
yeah! that's thought full.
but having a readme can help Github users to understand content properly.
 
However, I have a suggestion; can we make the content of **readme.md** and **index.md** same so that **index.md** can handle the **website**, and readme.md can work for **gh** users.

**Comment by KendallDoesCoding** [comment]
> However, I have a suggestion; can we make the content of readme.md and index.md same so that index.md can handle the website, and readme.md can work for gh users.

Good idea, however I may make a branch for github, but if the branch is named gh-pages it get's hosted, so maybe I'll just make a branch called main for now with the README.md, and gh-pages with index.md, what do you think?

**Comment by theabhayprajapati** [comment]
sure 😊

**Comment by KendallDoesCoding** [comment]
> > However, I have a suggestion; can we make the content of readme.md and index.md same so that index.md can handle the website, and readme.md can work for gh users.
> 
> Good idea, however I may make a branch for github, but if the branch is named gh-pages it get's hosted, so maybe I'll just make a branch called main for now with the README.md, and gh-pages with index.md, what do you think?

Done in [96992f6](https://github.com/KendallDoesCoding/Best-Hosting-Service/commit/96992f618ff06699e99a62c97b48b2cc2c8c0131). Thanks for the idea @theabhayprajapati.

**Pull request closed without merging**
